apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-commerce-service
  namespace: marketplace
  labels:
    app: commerce-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: commerce-service
  template:
    metadata:
      labels:
        app: commerce-service
    spec:
      containers:
        - name: commerce-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 5
            
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
