replicaCount: 1

image:
  repository: haze21/catalog-service
  pullPolicy: IfNotPresent
  tag: "d98a8cb4"

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

secretName: catalog-service-secret